[package]
name = "equivalence_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = { path = "../sqlparser-rs" }
rand_chacha = "0.3.1"
structopt = "0.3.26"
smol_str = "0.1.23"
logos = "0.12.1"
rand = "0.8.5"
regex = "1"